# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git_utils}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Glenn Nagel}]
  s.date = %q{2011-09-09}
  s.description = %q{A gem that provides simple git & gem utility scripts.}
  s.email = [%q{glenn@mercury-wireless.com}]
  s.homepage = %q{https://github.com/gnagel/mercury-wireless-public/tree/master/ruby/git_utils}
  s.post_install_message = %q{PostInstall.txt}
  s.rdoc_options = [%q{--main}, %q{README.rdoc}]
  s.require_paths = [%q{lib}]
  s.rubyforge_project = %q{git_utils}
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{A gem that provides simple git & gem utility scripts.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hoe>, [">= 2.1.0"])
      s.add_development_dependency(%q<hoe>, ["~> 2.9"])
    else
      s.add_dependency(%q<hoe>, [">= 2.1.0"])
      s.add_dependency(%q<hoe>, ["~> 2.9"])
    end
  else
    s.add_dependency(%q<hoe>, [">= 2.1.0"])
    s.add_dependency(%q<hoe>, ["~> 2.9"])
  end
end

