# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

BASE_DIR = File.dirname(__FILE__)

Gem::Specification.new do |s|
  s.authors = [%q{Glenn Nagel}]
  s.email = [%q{glenn@mercury-wireless.com}]

  s.name        = %q{git_utils}
  s.version     = File.readlines("#{BASE_DIR}/VERSION").first.strip
  s.description = %q{A gem that provides simple git & gem utility scripts.}
  s.summary     = s.description + " And aweseomness!"
  s.date        = `date '+%Y-%m-%d'`.lines.collect { |l| l.strip!; l }.first
  s.executables = `cd #{BASE_DIR}/bin && ls`.lines.collect { |l| l.strip!; l }
  s.files       = `cd #{BASE_DIR} && ls *.* **/*.*`.lines.collect { |l| l.strip!; l }.select { |file_name| !File.directory?(file_name) }

  s.extra_rdoc_files = ["Manifest.txt"]

  s.homepage             = %q{https://github.com/gnagel/mercury-wireless-public/tree/master/ruby/git_utils}
  s.post_install_message = %q{README.txt}
  s.rdoc_options         = [%q{--main}]
  s.require_paths        = [%q{lib}]

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.rubyforge_project = %q{git_utils}
  s.rubygems_version  = %q{1.8.6}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hoe>, [">= 2.1.0"])
      s.add_development_dependency(%q<hoe>, ["~> 2.12"])
    else
      s.add_dependency(%q<hoe>, [">= 2.1.0"])
      s.add_dependency(%q<hoe>, ["~> 2.12"])
    end
  else
    s.add_dependency(%q<hoe>, [">= 2.1.0"])
    s.add_dependency(%q<hoe>, ["~> 2.12"])
  end
end

